server:
  port: 8080
  servlet:
    context-path: /user-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ogabek
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        format_sql : true
  mail:
    host: smtp.gmail.com
    port: 465
    username: khamdamov343@gmail.com
    password: tigwncgwsjthmzpf
    properties:
      mail:
        smtp:
          auth: true
          ssl.enable: true
          starttls.enable: true
          debug: true
jwt:
  expiration: 10  # expiration in minutes
  refresh: 6      # refresh in months
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

